language: node_js
node_js:
- '5'
cache:
  yarn: true
sudo: required
addons:
  firefox: latest
notifications:
  email: false
before_install:
  - cd ..
  - git clone --depth=50 --branch=master https://github.com/jupyterlab/jupyterlab.git
  - cd jupyterlab
install:
  - pip install -e .
  - jlpm install
  - jlpm run add:sibling $TRAVIS_BUILD_DIR
  - jlpm install && npm run build
before_script:
  - cd packages && cd `basename $TRAVIS_BUILD_DIR`
  - jlpm run build:test
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - jlpm test
